### ISSUE TITLE
Does work with Python 3.7

### ISSUE THREAD

**Issue by MarkWieczorek** [pnnl/cmaputil#4]
Importing with Python 3.7 on osx, I get the following error:

~~~~
Python 3.7.0 (default, Jul 23 2018, 20:22:55) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import cmaputil
Traceback (most recent call last):

  File "/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-c8f3f7cf0886>", line 1, in <module>
    import cmaputil

  File "/usr/local/lib/python3.7/site-packages/cmaputil/__init__.py", line 7, in <module>
    from .cmaputil import *

  File "/usr/local/lib/python3.7/site-packages/cmaputil/cmaputil.py", line 186
    print 'Passed: ' + str([minJ, maxJ])
                   ^
SyntaxError: invalid syntax
~~~~
I think that you just need to 
~~~~
from __future__ import print_function as _print_function
~~~~
and then use the standard python3 print function.

**Comment by milankl** [comment]
I have a similar issue with python3.6

change line 186 of cmaputil.py to
```python
        print("Passed: " + str([minJ, maxJ]))
```
and line 394 to
```python
        print("Colormap failed. Try a different one!")
```
Support for python2 will be dropped in 2020...

**Comment by jamienunez** [comment]
Thanks for this! I will make these changes ASAP. Sorry for not seeing this sooner.

**Comment by jamienunez** [comment]
Looks like these changes have already been made in the repo but I need to update the install with pip. Marking as resolved.
